import{a as q,S as A,i as a}from"./assets/vendor-BNibzuFn.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))s(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function n(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(r){if(r.ep)return;r.ep=!0;const o=n(r);fetch(r.href,o)}})();const O="52783662-08dd67e4a79565a2d6e8bbcbe",C="https://pixabay.com/api/",f=15;async function y(e,t=1){const n={key:O,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:f,page:t};return(await q.get(C,{params:n})).data}const h=".gallery",$=".loader-backdrop",B=".load-more-wrapper",l=document.querySelector(h),m=document.querySelector($),M=document.querySelector(B),L=new A(`${h} a`,{captionsData:"alt",captionDelay:250});function b(e){if(!l||!Array.isArray(e)||e.length===0)return;const t=e.map(n=>{const{webformatURL:s,largeImageURL:r,tags:o,likes:c,views:S,comments:v,downloads:P}=n;return`
        <li class="gallery__item">
          <a class="gallery__link" href="${r}">
            <img class="gallery__image" src="${s}" alt="${o}" loading="lazy" />
            <div class="info">
              <p class="info__item"><b>Likes</b><span>${c}</span></p>
              <p class="info__item"><b>Views</b><span>${S}</span></p>
              <p class="info__item"><b>Comments</b><span>${v}</span></p>
              <p class="info__item"><b>Downloads</b><span>${P}</span></p>
            </div>
          </a>
        </li>
      `}).join("");l.insertAdjacentHTML("beforeend",t),L.refresh()}function T(){l&&(l.innerHTML="",L.refresh())}function _(){m&&m.classList.add("is-active")}function R(){m&&m.classList.remove("is-active")}function w(e){if(document.querySelector(".load-more"))return;const t=document.createElement("button");t.type="button",t.classList.add("load-more"),t.textContent="Load more",M.appendChild(t),t.addEventListener("click",e)}function d(){const e=document.querySelector(".load-more");e&&e.remove()}function x(){if(!l)return 0;const e=l.querySelector(".gallery__item");return e?e.getBoundingClientRect().height:0}const g=document.querySelector(".form"),D=g.querySelector('input[name="search-text"]');let p="",i=1,u=0;g.addEventListener("submit",H);async function H(e){e.preventDefault();const t=D.value.trim();if(!t){a.error({title:"Warning",message:"Please enter a search query.",position:"topRight"});return}p=t,i=1,u=0,d(),T(),_();try{const n=await y(p,i),s=n.hits||[];if(u=n.totalHits||0,!s.length){a.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}b(s),a.success({message:`Found ${u} images.`,position:"topRight"}),i*f<u?w(E):(d(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})),g.reset()}catch(n){console.error(n),a.error({message:"Something went wrong. Try again later.",position:"topRight"})}finally{R()}}async function E(){if(p){i+=1,_(),d();try{const t=(await y(p,i)).hits||[];if(!t.length){d(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"});return}b(t);const n=document.querySelectorAll(".gallery__item img"),s=Array.from(n).filter(o=>!o.complete).map(o=>new Promise(c=>{o.onload=o.onerror=c}));await Promise.all(s);const r=x();window.scrollBy({top:r*2,behavior:"smooth"}),i*f>=u?(d(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):w(E)}catch(e){console.error(e),i=Math.max(1,i-1),a.error({message:"Failed to load more images. Try again.",position:"topRight"})}finally{R()}}}
//# sourceMappingURL=index.js.map
