import{a as P,S as A,i as a}from"./assets/vendor-BNibzuFn.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const e of t)if(e.type==="childList")for(const c of e.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function o(t){const e={};return t.integrity&&(e.integrity=t.integrity),t.referrerPolicy&&(e.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?e.credentials="include":t.crossOrigin==="anonymous"?e.credentials="omit":e.credentials="same-origin",e}function i(t){if(t.ep)return;t.ep=!0;const e=o(t);fetch(t.href,e)}})();const O="52783662-08dd67e4a79565a2d6e8bbcbe",B="https://pixabay.com/api/",g=15;async function h(s,r=1){const o={key:O,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:g,page:r};return(await P.get(B,{params:o})).data}const L=".gallery",M=".loader-backdrop",$=".load-more",u=document.querySelector(L),d=document.querySelector(M),f=document.querySelector($),_=new A(`${L} a`,{captionsData:"alt",captionDelay:250});function b(s){if(!u||!Array.isArray(s)||s.length===0)return;const r=s.map(o=>{const{webformatURL:i,largeImageURL:t,tags:e,likes:c,views:R,comments:S,downloads:q}=o;return`
        <li class="gallery__item">
          <a class="gallery__link" href="${t}">
            <img class="gallery__image" src="${i}" alt="${e}" loading="lazy" />
            <div class="info">
              <p class="info__item"><b>Likes</b><span>${c}</span></p>
              <p class="info__item"><b>Views</b><span>${R}</span></p>
              <p class="info__item"><b>Comments</b><span>${S}</span></p>
              <p class="info__item"><b>Downloads</b><span>${q}</span></p>
            </div>
          </a>
        </li>
      `}).join("");u.insertAdjacentHTML("beforeend",r),_.refresh()}function T(){u&&(u.innerHTML="",_.refresh())}function v(){d&&d.classList.add("is-active")}function w(){d&&d.classList.remove("is-active")}function E(){f&&f.classList.add("is-visible")}function m(){f&&f.classList.remove("is-visible")}const y=document.querySelector(".form"),C=y.querySelector('input[name="search-text"]'),D=document.querySelector(".load-more");let p="",n=1,l=0;y.addEventListener("submit",x);D.addEventListener("click",H);async function x(s){s.preventDefault();const r=C.value.trim();if(!r){a.error({title:"Warning",message:"Please enter a search query.",position:"topRight"});return}p=r,n=1,l=0,m(),T(),v();try{const o=await h(p,n),i=o.hits||[];if(l=o.totalHits||0,!i.length){a.error({title:"",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}b(i),a.success({title:"",message:`Found ${l} images.`,position:"topRight"}),n*g<l?E():(m(),a.info({title:"",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})),y.reset()}catch(o){console.error(o),a.error({title:"",message:"Something went wrong. Try again later.",position:"topRight"})}finally{w()}}async function H(){if(p){n+=1,v();try{const r=(await h(p,n)).hits||[];if(!r.length){m(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"});return}b(r);const o=document.querySelectorAll(".gallery__item img"),i=Array.from(o).filter(e=>!e.complete).map(e=>new Promise(c=>{e.onload=e.onerror=c}));if(await Promise.all(i),document.querySelector(".gallery__item")){const e=document.querySelector(".gallery").firstElementChild.offsetHeight;window.scrollBy({top:e*2.3,behavior:"smooth"})}n*g>=l?(m(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):E()}catch(s){console.error(s),n=Math.max(1,n-1),a.error({message:"Failed to load more images. Try again.",position:"topRight"})}finally{w()}}}
//# sourceMappingURL=index.js.map
