import{a as q,S as A,i as a}from"./assets/vendor-BNibzuFn.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const c of t.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const O="52783662-08dd67e4a79565a2d6e8bbcbe",B="https://pixabay.com/api/",y=15;async function h(s,r=1){const o={key:O,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:y,page:r};return(await q.get(B,{params:o})).data}const _=".gallery",M=".loader-backdrop",$=".load-more",d=document.querySelector(_),m=document.querySelector(M),f=document.querySelector($),L=new A(`${_} a`,{captionsData:"alt",captionDelay:250});function b(s){if(!d||!Array.isArray(s)||s.length===0)return;const r=s.map(o=>{const{webformatURL:n,largeImageURL:e,tags:t,likes:c,views:S,comments:v,downloads:P}=o;return`
        <li class="gallery__item">
          <a class="gallery__link" href="${e}">
            <img class="gallery__image" src="${n}" alt="${t}" loading="lazy" />
            <div class="info">
              <p class="info__item"><b>Likes</b><span>${c}</span></p>
              <p class="info__item"><b>Views</b><span>${S}</span></p>
              <p class="info__item"><b>Comments</b><span>${v}</span></p>
              <p class="info__item"><b>Downloads</b><span>${P}</span></p>
            </div>
          </a>
        </li>
      `}).join("");d.insertAdjacentHTML("beforeend",r),L.refresh()}function T(){d&&(d.innerHTML="",L.refresh())}function R(){m&&m.classList.add("is-active")}function w(){m&&m.classList.remove("is-active")}function E(){f&&(f.style.display="block")}function u(){f&&(f.style.display="none")}const g=document.querySelector(".form"),C=g.querySelector('input[name="search-text"]'),D=document.querySelector(".load-more");u();let p="",i=1,l=0;g.addEventListener("submit",x);D.addEventListener("click",H);async function x(s){s.preventDefault();const r=C.value.trim();if(!r){a.error({title:"Warning",message:"Please enter a search query.",position:"topRight"});return}p=r,i=1,l=0,u(),T(),R();try{const o=await h(p,i),n=o.hits||[];if(l=o.totalHits||0,!n.length){a.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}b(n),a.success({message:`Found ${l} images.`,position:"topRight"}),i*y<l?E():(u(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})),g.reset()}catch(o){console.error(o),a.error({message:"Something went wrong. Try again later.",position:"topRight"})}finally{w()}}async function H(){if(p){i+=1,R();try{const r=(await h(p,i)).hits||[];if(!r.length){u(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"});return}b(r);const o=document.querySelectorAll(".gallery__item img"),n=Array.from(o).filter(t=>!t.complete).map(t=>new Promise(c=>{t.onload=t.onerror=c}));await Promise.all(n);const e=document.querySelector(".gallery__item");if(e){const t=e.getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}i*y>=l?(u(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):E()}catch(s){console.error(s),i=Math.max(1,i-1),a.error({message:"Failed to load more images. Try again.",position:"topRight"})}finally{w()}}}
//# sourceMappingURL=index.js.map
